### ISSUE TITLE
Corrección Mercado Liebre TVP

### ISSUE THREAD

**Issue by tvandenp** [crinlancelot/mercado-liebre#1]
1. [] Cumple
   Detalle: OK
2. [] Cumple
   Detalle: Ok
3. [] Cumple
   Detalle:  Ok, todo acomodado
4. [] Cumple
   Detalle: Ok register
5. [] Cumple
   Detalle: Ok login
6. [] Cumple
   Detalle: Arroja error, cumple OK!
7. [] Cumple
   Detalle: OK
8. [] Cumple
   Detalle: Ok animaciones truck y descripción de productos
9. [] Cumple
   Detalle: Cumple con todas las consignas de gran manera, mucho orden en el posicionamiento de todos los objetos. 
10. [] Cumple
    Detalle: Mínimos detalles estéticos que podrían mejorarse:
- Tamaño logo desktop
- Alineación main navbar desktop
- Mantener estilo header en plantilla login / register

**Comment by crinlancelot** [comment]
Ya ajuste el tamaño del logo.
Me gusta el main navbar como lo puse así que lo dejé así.
No mantuve el estilo de la plantilla porque eso lo vamos a hacer después con EJS o con React
